var GAME_LEVELS = [
["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 "x          yyyyy                     yyyyy                     yyyyy                    x",
 "x           yyy                       yyy                       yyy                     x",
 "x            y                         y                         y                      x",
 "x                                                                                       x",
 "x                                                                                       x",
 "x                                                                                       x",
 "x                                                                                       x",
 "x                                                                                       x",
 "x                                                                                       x",
 "x                                                                                       x",
 "x                                                                       o               x",
 "x                                                                                     Q x",
 "x                                                                                    xxxx",
 "x                                                                o          x        xxxx",
 "x           Q                                                   xxx             xxx  xxxx",
 "x           x           o          QQ                     xxx                        xxxx",
 "x         xxxxx                    xx               xxx                xxx           xxxx",
 "x  @    xxxxxxxxx            j  tx    x       xxx                                    xxxx",
 "xxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxx    xxxxxxx                      xxxxxxxxxxxxxxxxxxxxxx",
 "xxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxx    xxxxxxx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxx",
 "xxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxx!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxx",
 "xxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxx!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxx",
 "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

 ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "x    yyyyy              yyyyy                           yyyyy                           x",
  "x     yyy                yyy                             yyy                            x",
  "x      y                  y                               y                             x",
  "x                                                                                     Q x",
  "x                                                                                    xxxx",
  "x                                                                o                   xxxx",
  "x                                                               xxx                  xxxx",
  "x                            xx                                                      xxxx",
  "x                                                   xxx                              xxxx",
  "x  @      j                               j                                      j   xxxx",
  "xxxxxxxxxxxxxxxxxxxxxxx               xxxxxxx                      xxxxxxxxxxxxxxxxxxxxxx",
  "xxxxxxxxxxxxxxxxxxxxxxx               xxxxxxx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxx",
  "xxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxx",
  "xxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxx",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                                                       x",
   "x                                                                       o               x",
   "x                                                                                     Q x",
   "x                                                                                    xxxx",
   "x                                                                o                   xxxx",
   "x                                                               xxx                  xxxx",
   "x                                                                                    xxxx",
   "x                                                                      xxx           xxxx",
   "x  @          t                                                                 j    xxxx",
   "xxxxxxxxxxxxxxxxxxxxxxx                                            xxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxx                                            xxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
 ];

 if (typeof module != "undefined" && module.exports)
   module.exports = GAME_LEVELS;
